"""app

Revision ID: 643bc9ec6899
Revises: 
Create Date: 2024-11-24 09:54:16.691594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643bc9ec6899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google', schema=None) as batch_op:
        batch_op.drop_constraint('google_auth_id_key', type_='unique')
        batch_op.drop_constraint('google_auth_id_fkey', type_='foreignkey')
        batch_op.drop_column('auth_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('google_auth_id_fkey', 'auth', ['auth_id'], ['id'])
        batch_op.create_unique_constraint('google_auth_id_key', ['auth_id'])

    # ### end Alembic commands ###
