"""match

Revision ID: a791b31fa357
Revises: fea5cd917c24
Create Date: 2024-11-02 10:35:41.684369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a791b31fa357'
down_revision = 'fea5cd917c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=1000), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_constraint('profile_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.create_unique_constraint('profile_user_id_key', ['user_id'])

    op.drop_table('match')
    # ### end Alembic commands ###
